### ISSUE TITLE
Suggestion: Possibility to use queuing systems

### ISSUE THREAD

**Issue by kipal1988** [3DGenomes/TADbit#107]
It would be really great if a class can be made to deploy on popular queuing systems such as lsf and SGE such as the one we are using. Currently, I am chunking the files myself and running the jobs on our cluster like that, because threads option do not really do well with clusters.

**Comment by MarcoDiS** [comment]
This email address will be deactivated shortly, please use: marco.distefano@cnag.crg.eu

**Comment by fransua** [comment]
This is indeed a good idea.
Will try to think on something generic (we are here using slurm), or at least able to prepare the files, generate list of jobs, and collect the result.
thanks!
