### ISSUE TITLE
Suggestion: A int or str check can be provided for checking the var type of arguments coming from the command line

### ISSUE THREAD

**Issue by kipal1988** [3DGenomes/tadbit#108]
When using the pytadbit.mapping.mapper class on our cluster I built a bash wrapper for splitting the files and passing them onwards to a python wrapper built on top of the pytadbit.mapping.mapper class.

pytadbit/mapper/mapper.py line 170
```python
if (len(zip(range_start, range_stop)) < len(range_start) or len(range_start) != len(range_stop)):
        raise Exception('ERROR: range_start and range_stop should have the ' +
                        'same sizes and windows should be uniques.')
```

Offending values were the range-start and range-stop values in iterative_mapping.
It expects an object containing integer values. zipping it and then checking if the number of value pairs, this presents a problem if the values are coming from the command line, as by default such values are of vartype string.

This presents an ambiguity, which gives the user no idea about what the problem actually is. A condition can be added within the existing one which checks if the variable is of a correct vartype. if it is a string it can report that It expects an int type object instead of a string or a float for that matter, because I think a float would produce a problem later on when it's getting the chunks.

**Comment by fransua** [comment]
Hi @kipal1988 ,
thanks for the suggestion, let me know if this commit fixes it
