### ISSUE TITLE
TEST FAILED

### ISSUE THREAD

**Issue by dreamingest** [3DGenomes/TADbit#112]
Dear ‘TADBit’ developers, Thanks for developing ‘TADBit’! It is of a great interest for us to be able to discover TADs. We have installed 'TADBit' followed the documentation. But when we ran test script to check that the installation, we got the message:

-----------
/usr/local/lib/python2.7/site-packages/pytadbit/parsers/hic_parser.py:79: UserWarning: WARNING: found header
  warn('WARNING: found header')
............./usr/local/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py:71: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py:83: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py:95: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py:117: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
FF.

C SIDE
------
rm -f testset *.o *.gcda *.gcno *.gcov gmon.out analysis.txt \
		callgrind.out.* cache.txt
gcc -I.. `pkg-config --cflags glib-2.0` -g -pg -Wall -std=gnu99 -O0 -fstrict-aliasing -fprofile-arcs -ftest-coverage   -c -o tadbit.o ../tadbit.c
gcc -I.. `pkg-config --cflags glib-2.0` -g -pg -Wall -std=gnu99 -O0 -fstrict-aliasing -fprofile-arcs -ftest-coverage    testset.c tadbit.o  `pkg-config --libs glib-2.0` -lpthread -lm -o testset
gtester --verbose --keep-going testset
TEST: testset... (pid=18222)
  /ll:                                                                 OK
  /enforce_symmetry:                                                   OK
  /tadbit:                                                             OK
PASS: testset
.
======================================================================
FAIL: test_15_3d_modelling (__main__.TestTadbit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_all.py", line 479, in test_15_3d_modelling
    [0, 2, 3, 4, 4])
AssertionError: Lists differ: [0.0, 3.0, 3.0, 4.0, 4.0] != [0, 2, 3, 4, 4]

First differing element 1:
3.0
2

- [0.0, 3.0, 3.0, 4.0, 4.0]
+ [0, 2, 3, 4, 4]

======================================================================
FAIL: test_16_models_stats (__main__.TestTadbit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_all.py", line 537, in test_16_models_stats
    self.assertEqual([16], model.inaccessible_particles(1000))
AssertionError: Lists differ: [16] != [11, 16]

First differing element 0:
16
11

Second list contains 1 additional elements.
First extra element 1:
16

- [16]
+ [11, 16]

----------------------------------------------------------------------
Ran 17 tests in 11.037s

FAILED (failures=2)

We would be very appreciable if you could advise us what could be amend in our procedure in order to perform a successful ‘TADBit’ run.
Thank you again.

**Comment by fransua** [comment]
Hi @dreamingest ,
the problem your reporting is probably due to a different version of IMP. The test that is failing is relative to modeling only and it's due to the fact that "random seeds" used for modeling with IMP are not compatible between version, and the resulting 3D models are thus slightly different.
And although, this issue will not affect your analysis, it is definitively something that needs to be fixed. I will mark it as enhancement, and try to make the test less sensible to IMP version in a near future.
thanks for reporting it.

**Comment by fransua** [comment]
using conda to install IMP should solve this issue.

`conda install -c https://conda.anaconda.org/salilab imp`
