### ISSUE TITLE
question regarding pytadbit.parsers.sam_parser

### ISSUE THREAD

**Issue by kipal1988** [3DGenomes/TADbit#114]
Hi fransua,

I have been using your package to analyze some HiC data and I went from the alignment to parse_sam() which provides the read counts per fragments for each mate pair. I was looking for the headers of the read counts file, till now I know that 0 and 1 must correspond to strand information but the rest is greek to me, so i went searching for the description of that function in the docs and it doesn't seem to be there under the parsers. Can you please clarify what the columns are in the read counts file?

**Comment by kipal1988** [comment]
never mind, I looked into the pytadbit lib hierarchy and found the column names. But still it would be great if the docs had the description of the function and what it outputs.

**Comment by fransua** [comment]
Hi @kipal1988 ,
your right, I will complete the documentation of this part.
thanks for reporting.
