### ISSUE TITLE
Understanding how TADBit Works

### ISSUE THREAD

**Issue by kipal1988** [3DGenomes/TADbit#125]
HI Fransua,

We are running some large scale analysis pipelines where we are using TADBit for TAD Calling, our jobs number around some 900 jobs and we would really like to optimize the main bottleneck in the pipeline which is the computation time taken by TADBit.

Currently I am running TADBit with 50 threads, and so from the behaviour of the pipeline I understand it is not using something like MPI for parallelization but rather it uses process forks. Some questions I had regarding this are as follows.

1. What is the exact step that is being parallelized?
2. Have you ever done a comparison as to how long a job might take on a single thread vs multi-thread? and how that correlates with increasing resolution.

I have been wondering if the speed gain is actually 2x? so if a process takes 100 secs on 1 thread then will it take 2 secs on 50?

**Comment by fransua** [comment]
Hi @kipal1988 ,
 1. The algorithm searches for different number of breakpoints ,each of these searches is done on a different CPU.
 * According to @gui11aume who implemented the algorithm, the speed gain is not exactly 2x for 2x more CPU, but quite near. We never tried with more than 8 CPUs.

cheers
