### ISSUE TITLE
gap in tutorial: from mapping to tad

### ISSUE THREAD

**Issue by robinweide** [3DGenomes/TADbit#126]
Hi all,

I followed the [first part](https://3dgenomes.github.io/TADbit/tutorial/tutorial_0_mapping.html) of the tutorial and saved my matrix with the HiC_data.write_matrix() function. However, it is not clear (to me) how to proceed with the  [second part](https://3dgenomes.github.io/TADbit/tutorial/tutorial_1_general.html). How do I read my saved matrix with add_experiment()?

Thanks,

Robin

**Comment by fransua** [comment]
Hi @robinweide 
It's true, there is still a gap in the documentation at this point.
However the file(s) you generated with the "HiC_data.write_matrix" function are fully compatible with the part of the tutorial:
http://3dgenomes.github.io/TADbit/tutorial/tutorial_1_general.html#hi-c-data-format 

you can load the files under the hic_data parameter if raw, or under the norm_data parameter if normalized (I recommend you load both, raw and normalized data).

Let me know is this help, the documentation will clarify this point soon.

thanks
