### ISSUE TITLE
Problem with masking columns

### ISSUE THREAD

**Issue by apaytuvi** [3DGenomes/TADbit#158]
Hi @fransua 

I load reads to matrix, with resolution 100.000:

`hic_data2 = load_hic_data_from_reads(reads, resolution=100000)`

Then, I try to filtering columns with low count number:

`hic_data2.filter_columns(draw_hist=True,savefig="BL6_filter_columns.png")`

And it outputs this pic:

![bl6_filter_columns](https://cloud.githubusercontent.com/assets/11228225/20425770/6dff64b2-ad7c-11e6-8559-fac7adc3ac49.png)

According to the image, it will remove those columns with less than ~1.000 counts. The problem is that, out of ~26.000 columns, it will filter ~25.000 columns, the vast majority. This should not happen according to the image, right? What is going on?

**Comment by fransua** [comment]
Hi @apaytuvi 
by default the filtering (http://3dgenomes.github.io/TADbit/reference/reference_hic_data.html#pytadbit.parsers.hic_parser.HiC_data.filter_columns) consists in two steps.

1. columns with more than a given percentage of zeros are filtered out (by default perc_zero=75)
2. this more fine tuning filtering is applied

It is probable that it is the first step that removes most of your columns, you could try to increase the percentage of zeros, or use an other parameter that is min_count (set min_count=10 if your matrix is very sparse).

Filtering bins with low number of reads is very important i the context of "full" ICE normalization, but if you are doing only one round (iterations=0) than it should have almost no effect.

hopes this helps

cheers

**Comment by apaytuvi** [comment]
Thank you @fransua 

with `min_count=10`:

`Found 2013 of 27269 columns with poor signal`.

Around ~7% of columns will be masked. Is it OK?

**Comment by fransua** [comment]
very good I guess, around 8% of the bases in human assembly are Ns :)

**Comment by apaytuvi** [comment]
well, it's mouse! mm9 @fransua

**Comment by fransua** [comment]
should be very similar :)
