### ISSUE TITLE
min_count in filter_columns

### ISSUE THREAD

**Issue by apaytuvi** [3DGenomes/TADbit#160]
By doing:

```
genome = Chromosome(name="genome")
#loading data
genome.add_experiment("ago", hic_data=([matrix.tolist()]), resolution=40000)
#filtering columns
exp = genome.experiments["control"].filter_columns(draw_hist=False,min_count=10,savefig="filter_columns.png")
```

being matrix a numpy matrix, it throws:

`TypeError: filter_columns() got an unexpected keyword argument 'min_count'`

I did use `min_count` and `filter_counts()` properly in the past, but from:

```
hic_data = load_hic_data_from_reads(reads, resolution=40000)
hic_data.filter_columns(draw_hist=True)
```

**Comment by fransua** [comment]
Hi @apaytuvi ,
indeed I think this was a past issue, can you let me know the version of TADbit you are using, and if an update fixes it?
thanks
francois

**Comment by apaytuvi** [comment]
fixed, thanks!
