### ISSUE TITLE
What is maxdist exactly?

### ISSUE THREAD

**Issue by SHZ66** [3DGenomes/TADbit#165]
Hi,

I am trying to understand this maxdist parameter. Based on the tutorial it is "maximal distance between two non-interacting particles". So I would imagine this number can be really large (e.g. the diameter of a chromosome). However, the range is set to 2000～3500 (i.e. `maxdist_range=(2000, 3500, 500)` in tutorial), which is very close to `cutoff=2000`. If my understanding is correct, cutoff is the distance that two fragments will be considered as interacting, which should be a relatively short distance. So why maxdist is close to cutoff? Any explanation would be appreciated. Thanks.

**Comment by fransua** [comment]
Hi,
yes you understood correctly. maxdist goes from the contact, which is 2 times the radius of a modeled particle (a fragment), to the diameter of the nuclei (in eukaryotes :)). The radius of a particle depends on the resolution and on the scale parameter, which is usually set 0.01 nm per nucleotide. At 100 kb the minimum maxdist you can set is thus 100.000 times 0.01, 1000 nm.
It's true that 2000 is thus a relatively small number, however Hi-C is about contact and it is thus, in our opinion, a good strategy to start the optimization with small values of maxdist.
And it is true that having the cutoff set at the same distance as the maxdist seems not ideal. However the cutoff is also a parameter that can be optimized, if you feel that the cutoff could be smaller you can try starting at smaller values (optimizing the cutoff is relatively fast as it is done without computing new models). I should comment this in the tutorial.
cheers

**Comment by SHZ66** [comment]
Thank you very much. That perfectly answered my question.
