### ISSUE TITLE
find compartments clarification

### ISSUE THREAD

**Issue by apaytuvi** [3DGenomes/TADbit#166]
Hi @fransua 

according to `find_compartments`,

```
Search for A/B copartments in each chromsome of the Hi-C matrix.
        Hi-C matrix is normalized by the number interaction expected at a given
        distance, and by visibility (one iteration of ICE).
```

Prior to compartment finding, I normalize my matrix this way:

```
hic_data.normalize_hic(iterations=50, max_dev=0.01, silent=True)
```

and the function `find_compartments` will use the normalized values from this step, as I can see this piece of code in the function:

```
        if not self.bias:
            if kwargs.get('verbose', False):
                print 'Normalizing by ICE (1 round)'
            self.normalize_hic(iterations=0,
                               silent=not kwargs.get('verbose', False))
```

I wonder:

**It is necessary to perform just 1 iteration prior to compartment finding? Is it OK if I perform normalization with more than 1 iteration?** If not, why?

Thank you.

**Comment by fransua** [comment]
Hi @apaytuvi ,
ICE normalization provided by TADbit is designed to converge, that is to reach the point where the sum of all columns in the matrix are equal (generally a bit more than 10 iterations).
However depending on the density of your data, and on the features you want to look at, this convergence might not be adequate.
We usually use only one iteration for all our analysis, however this is completely up to the user.
I recommend you to try with both strategies, try to spot the differences and assess what would be better for your data. But if you had to pick one now, I would recommend you to use only 1 iteration. If your matrix is not dense enough ICE convergence could never be reached (even with 50 iterations), and, on the other hand, it can be argued that some biological signal consists of the differences between the sum of the columns in which case the convergence could wipe this information.
cheers
