### ISSUE TITLE
TADbit model

### ISSUE THREAD

**Issue by TonyWoody** [3DGenomes/TADbit#179]
Dear Francois,

Thank you for developing TADbit. I am a green hand at bioinformatics. Now, I am trying to learn Hi-C data processing. I installed TADbit but the model function could not be exported:

usage: tadbit [-h]
              {map,parse,filter,describe,clean,normalize,merge,segment} ...

I guess the reason must be i did not install TADbit properly, as there were some failures after running test_all.py:

C SIDE
------
rm -f testset *.o *.gcda *.gcno *.gcov gmon.out analysis.txt \
	callgrind.out.* cache.txt
gcc -I.. `pkg-config --cflags glib-2.0` -g -pg -Wall -std=gnu99 -O0 -fstrict-aliasing -fprofile-arcs -ftest-coverage   -c -o tadbit.o ../tadbit.c
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
gcc -I.. `pkg-config --cflags glib-2.0` -g -pg -Wall -std=gnu99 -O0 -fstrict-aliasing -fprofile-arcs -ftest-coverage    testset.c tadbit.o  `pkg-config --libs glib-2.0` -lpthread -lm -o testset
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
In file included from testset.c:1:0:
test.h:4:18: fatal error: glib.h: No such file or directory
 include <glib.h>
                
compilation terminated.
make: *** [testset] error 1
gcc -I.. `pkg-config --cflags glib-2.0` -g -pg -Wall -std=gnu99 -O0 -fstrict-aliasing -fprofile-arcs -ftest-coverage    testset.c tadbit.o  `pkg-config --libs glib-2.0` -lpthread -lm -o testset
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
In file included from testset.c:1:0:
test.h:4:18: fatal error: glib.h: No such file or directory
 include <glib.h>
                
compilation terminated.
make: ***[testset] error 1
ERROR problem with C test
F

======================================================================
FAIL: test_15_3d_modelling (__main__.TestTadbit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_all.py", line 556, in test_15_3d_modelling
    [0, 2, 3, 3, 3])
AssertionError: Lists differ: [0.0, 2.0, 2.0, 3.0, 4.0] != [0, 2, 3, 3, 3]

First differing element 2:
2.0
3

- [0.0, 2.0, 2.0, 3.0, 4.0]
+ [0, 2, 3, 3, 3]

======================================================================
 FAIL: test_16_models_stats (__main__.TestTadbit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_all.py", line 642, in test_16_models_stats
    self.assertEqual([11, 15, 16], model.inaccessible_particles(1000))
AssertionError: Lists differ: [11, 15, 16] != [4, 11, 16]

First differing element 0:
11
4

- [11, 15, 16]
+ [4, 11, 16]

======================================================================
FAIL: test_20_tadbit_c (__main__.TestTadbit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_all.py", line 801, in test_20_tadbit_c
    self.assertEqual(True, False)
AssertionError: True != False

----------------------------------------------------------------------

I tried to fix these failures by myself, such as installing IMP and glib by conda, but nothing help.
Could you please help me?

Thank You,
Tian

**Comment by fransua** [comment]
Hi @TonyWoody ,
I think you are all good, the test fails here probably because of a different version of IMP which causes the random seeding to start differently.
(there is also an other issue with missing glib, but this library is only used for testing purposes)
TADbit is well installed :)
cheers

**Comment by yangqihang1230** [comment]
"I encountered the same problem. I installed TADbit but couldn't export the model function. I can run the test set normally. Has your problem been solved?"

Let me know if you need furth




(py37) $ tadbit -h
usage: tadbit [-h]
              {map,parse,filter,describe,clean,normalize,bin,export,import,merge,segment}
              ...

optional arguments:
  -h, --help            show this help message and exit

AVAILABLE PROGRAMS:
  {map,parse,filter,describe,clean,normalize,bin,export,import,merge,segment}
    map                 Map Hi-C reads and organize results in an output
                        working directory
    parse               Parse mapped Hi-C reads and get the intersection
    filter              Filter parsed Hi-C reads and get valid pair of reads
                        to work with
    describe            Describe jobs and results in a given working directory
    clean               Delete jobs and results of a given list of jobids in a
                        given directories
    normalize           normalize Hi-C data and generates array of biases
    bin                 bin Hi-C data into matrices
    export              export Hi-C data to other formats
    import              import Hi-C data to TADbit toy BAM
    merge               load two working directories with different Hi-C data
                        samples and merges them into a new working directory
                        generating some statistics
    segment             Finds TAD or compartment segmentation in Hi-C data.
