### ISSUE TITLE
when testing: ImportError: No module named pytadbit

### ISSUE THREAD

**Issue by chrisclarkson100** [3DGenomes/TADbit#185]
Hi, apologies in advance for the inexperienced question but I cloned your directory and everything seemed to work fine (git clone https://github.com/3DGenomes/TADbit) but when I run the test_all.py script, at first I got the following power:
'ImportError: No module named pytadbit' i thought this might be due to an old version of numpy and I upgraded numpy on my linux. However when I re-ran it, I got: ImportError: No module named pytadbit....
I googled this and pytadbit is a part of your software.... so how can it be missing when that's exactly what I cloned?

**Comment by fransua** [comment]
Hi,
after cloning the repo you should enter the directory, and type:
`python setup.py install`
or, if you are installing your python packages as root:
`sudo python setup.py install`

**Comment by chrisclarkson100** [comment]
Hi thanks for such a quick response,
 I used your advice: sudo python setup.py install (I had to do it this way as I do not own the computer and got a permissions error without typing sudo) everything seemed to work fine but when I run the test_all.py script I get the same error again.... I tried cloning the whole repository again and starting from scratch but still the same error prevails.

**Comment by fransua** [comment]
lets do this by mail if you don't mind serra.francois@gmail.com
can you paste me by mail all the output in your screen during the installation?
thanks

**Comment by chrisclarkson100** [comment]
Thanks so much for this, I will email you from my college email cc16956@essex.ac.uk

**Comment by fransua** [comment]
The issue was due to conflicts between system vs conda installation of python libraries
