### ISSUE TITLE
Using bowtie2 instead of GEM mapper

### ISSUE THREAD

**Issue by apredeus** [3DGenomes/TADbit#189]
Hello all, 

we are having a complete hell of a time installing and running GEM mapper on various servers, and their support is not very helpful. 

What is changed if one is using bowtie2 - e.g. what settings are supposed to be passed to the mapper, etc? Are there any obvious drawbacks of using bowtie2 instead of GEM? I know that iterative mapping have been used for processing Hi-C experiments; can this be done with bowtie2 as well? 

Sorry if this is not the right place to ask, I looked for a google group or something like that and could not find it. 

Thank you in advance!

**Comment by fransua** [comment]
Hi,
yes,we should open a google group for this.
So no, no particular reason on why to prefer GEM over bowtie2, both gave us similar results. The main reason is that we have the GEM developers next-door.
Other Hi-C pipelines use bowtie2,and implement both iterative, or fragment based mapping.
If you need specific features from TADbit you can always come back after the mapping with your SAM files and parse them with the function [parse_sam.](https://3dgenomes.github.io/TADbit/reference/reference_parser.html#pytadbit.parsers.sam_parser.parse_sam)

**Comment by apredeus** [comment]
Dear Fransua, 

Should I use a thrid-party mapper like bowtie2, what options would you use (I'd imagine they would be quite different for Hi-C), and how do you proceed from there?

**Comment by fransua** [comment]
I did it only a couple of times, and only through [hiclib](https://bitbucket.org/mirnylab/hiclib).
You can have a look there at the parameters they are using.
cheers
