### ISSUE TITLE
Compartments and TADbit

### ISSUE THREAD

**Issue by apaytuvi** [3DGenomes/TADbit#192]
I have `HiC-Pro`:
- a bed file containing `chromosome`, `start`, `end`, `bin`
```
chr1	0	40000	1
chr1	40000	80000	2
chr1	80000	120000	3
...
```
- a .matrix file containing the interactions `bin1`, `bin2`, `counts`
```
1	1	3
1	681	1
1	6123	1
...
```
I designed this function to load the data to TADbit:
```
def load_hic_data_from_hicpro(infile, resolution, chromsizes):
	#chromosome stuff
	genome_seq = {} #we store here chromosome bins
	size = 0 #total size of genome in terms of bins

	sections = []
	substract = 0
	dict_sec = dict()
	#reading bed
	f = open(chromsizes, "r")
	for line in f:
		sline = line.strip("\n").split("\t")
		if sline[0] not in genome_seq:
			substract = int(sline[3])
		binInChr = int(sline[3]) - substract + 1
		genome_seq[sline[0]] = binInChr
		#dict_sec[(sline[0], binInChr)] = int(sline[3])
		sections.append((sline[0], binInChr-1))
		size += 1
	f.close()
	dict_sec = dict([(j, i) for i, j in enumerate(sections)])
	#reading matrix
	imx = HiC_data((), size, genome_seq, dict_sec, resolution=resolution)
	f =  open(infile, "r")
	for line in f:
		sline = line.strip("\n").split("\t")
		imx[int(sline[0])-1, int(sline[1])-1] += int(sline[2])
		imx[int(sline[1])-1, int(sline[0])-1] += int(sline[2])
	f.close()
	return imx, sections, size
```
where the `infile` is the `matrix` file and `chromsizes` the `bed` file.

The final aim is to call compartments, so after calling the function above, I call the following function:

```
hic_data, sections, size = load_hic_data_from_hicpro(file, args.resolution, args.chromsizes)
eigenvectors = hic_data.find_compartments(label_compartments="none")
```

When plotting chromosome Y (**this is human data**), it looks like this:

![chry](https://user-images.githubusercontent.com/11228225/30964825-38fcfa94-a453-11e7-9cd9-a235e33fd8ed.png)

It seems quite OK to me, since it's chromosome Y. However, the eigenvalues look like this:

![chry](https://user-images.githubusercontent.com/11228225/30964844-51952b44-a453-11e7-9680-c46252bc0329.png)

How is that possible? Am I doing something wrong loading my data to TADbit?

And chromosome 11 looks like this:

![chr11](https://user-images.githubusercontent.com/11228225/30965203-cccbcbdc-a454-11e7-9764-90d861ec3185.png)

Is it all right?

Thank you.

**Comment by fransua** [comment]
Hi,
it seems that the problem comes from a wrong indexing of the chromosomes (`genome_seq` in your script). This dictionary should be and `OrderedDict`, so just do:
```
from collections import OrderedDict
genome_seq = OrderedDict() #we store here chromosome bins

```

**Comment by apaytuvi** [comment]
@fransua Thank you, that worked!! :D
