### ISSUE TITLE
question for the conversion of TAD bin coordinates into genomic coordinates

### ISSUE THREAD

**Issue by mzufferey** [3DGenomes/TADbit#196]
Dear All,

I have a question regarding the conversion of TAD bin coordinates (as outputed from write_tad_borders) into genomic coordinates.
If for example, for a 40kb resolution experiment, write_tad_borders returns, 
start  end  score
1  2  10.0
3  5  8.0
Is it correct to interpret it as follows:
tad1 ranges from 1 to 80000
tad2 ranges from 80001 to 200000 ?

Thank you in advance and best regards.

**Comment by fransua** [comment]
Hi,
it is exactly this yes :)

**Comment by mzufferey** [comment]
Thank you a lot for your quick reply. But, sorry, another question has now emerged...
Is it normal that the TADs could be overlapping ? I haven't noticed before, and it only happens to me once, as I obtained the following output (for the write_tad_borders function):
[...]
58	60	10.0
60	63	10.0
[---]
If I follow the same rules as above [i.e. (startBin-1)*binSize + 1 for the starts ; endBin*binSize for the ends], this would give
tad1 ranges from 2280001 to 2400000
tad2 ranges from 2360001 to 2520000

Ideally, for further downstream analyses, I would need strictly non-overlapping TAD coordinates. Do you have any suggestion for the conversion in this case ?

Many thanks !

**Comment by fransua** [comment]
Hi,
this might be an unexpected behavior indeed.
would it be possible for you to send me the matrix by email in order to try to reproduce this mistak and check what is happening?
thanks
