### ISSUE TITLE
running tadbit segment on full chrom matrix (all chroms) ? 

### ISSUE THREAD

**Issue by samadelk** [3DGenomes/TADbit#218]
Dear TADbit developper, 
Thank you for this tools. 
I wonder if there is a way to perform TAD finding using "tadbit segment" tool on a matrix containing the whole chromsomes interactions (trans & cis)? 
In addition, when i try to perform a test on my own data, i get the following errors : 

Traceback (most recent call last):
packages/pytadbit/tools/tadbit_segment.py", line 43, in run
    bad_co = path.join(opts.workdir, bad_co)
  File "/homeniolon/eq_esol/tools/miniconda2/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

my bash command: $python_path $TADbit segment -w $wdPath --nosql --mreads $path_validPairs -r 100000 --norm_matrix $icedMatrix --raw_matrix $rawMat

any suggestion will be precious for me
thank you 
Samad

**Comment by fransua** [comment]
Hi @samadelk 
sure, that's the idea :)
However tools are relatively unsafe in the master branch... I would recommend you to switch to the most recent [dev branch](https://github.com/3DGenomes/TADbit/tree/dev) ([switch to remote branch](https://stackoverflow.com/questions/67699/how-to-clone-all-remote-branches-in-git/72156#72156))
I fact the flags --norm_matrix and --raw_matrix are not connected to anything inside the script... it's a "to be implemented" feature (that is also still missing in the dev branch)... I will actually remove the options for now.

The simplest solution I could recommend you is to write a simple python script based on the API documentation:

```
from pytadbit import Chromosome

chrom = Chromosome('chr1')
my_chrom.add_experiment('k562', hic_data="$path_validPairs", norm_data=" $icedMatrix", resolution=100000)
my_chrom.find_tad('k562', n_cpus=8)

print my_chrom.experiments['k562'].write_tad_borders()

```

I you still wish to use tadbit tools I would recommend you to switch to the dev branch, convert your $path_validPairs into a special BAM file using the provided script [tsv2bam.py](https://github.com/3DGenomes/TADbit/blob/dev/scripts/tsv2BAM.py) (slowest step)

then use `tadbit normalize -w workpath1 --bam $new_bam -r 100000`
and then just `tadbit segment -w workpath1 --only_tads`

**Comment by samadelk** [comment]
Hi Francois, 
I appreciate your quick reply, thank you. 
I tried also the python script by creating the Chrmosome subject based on the API documentation. My question here is, can I use the whole matrix and store it in a "Chromosome" subject or I have to create for each chromosome its own matrix and run the script separately ?
Cheers,

**Comment by fransua** [comment]
Hi @samadelk ,
it really depends on the analysis you want to perform afterwards. I guess you ideally want to store genomic normalized matrices, if so perhaps you can follow the step in this part of the tutorial, that uses HiC_data objects: https://3dgenomes.github.io/TADbit/tutorial/tutorial_0_mapping.html#filtering-and-normalization.
cheers
