### ISSUE TITLE
Mapping multiple libraries

### ISSUE THREAD

**Issue by mictadlo** [3DGenomes/TADbit#262]
Hi,
I have the following Hi-C data which are based on multiple libraries:

```
> ls -1
N_Ben_HiC2.R1.fq.gz
N_Ben_HiC2.R2.fq.gz
N_Ben_HiC4.R1.fq.gz
N_Ben_HiC4.R2.fq.gz
```

How could I use them with TADbit?

Thank you in advance.

Michal

**Comment by fransua** [comment]
Hi Michal,
easy, first you map each separately (labelling with read=1, and read=2 properly),
then you feed parse_map function with all files at once (see: https://3dgenomes.github.io/TADbit/tutorial/tutorial_0_mapping.html#map-parsing)
mapped_r1, would be a list with all output, from all *.R1.fq.gz, together and mapped_r2 all outputs from the mapping of all the *.R2.fq.fz

cheers

**Comment by mictadlo** [comment]
Hi,
Is it possible to do it with TADit tool?

Thank you in advance,

Best wishes,

Michal

**Comment by fransua** [comment]
sure, even easier. You just map all you need using the **same working directory** and making sure to label correctly which end (with `--read 1` or` --read 2`).

And then just run `tadbit parse workdir --genome PATH_TO_GENOME.fasta`
TADbit will search for all mapped reads in the workdir using the local database and join everything (check the output printed, it should explain a bit what it is doing :slightly_smiling_face: ).
