### ISSUE TITLE
Mapping step fail due to gem parameters 

### ISSUE THREAD

**Issue by dawe** [3DGenomes/TADbit#275]
I’m testing TADbit for the first time, apparently I’m not able to create genome alignments due to gem-mapper command line options which are not correctly passed by the full_mapping function 

```
mapped_r1 = full_mapping(genome, r1, 'test_r1', windows=(1, 150), r_enz=['MboI', 'HinfI'], frag_map=True, nthreads=8, clean=True, temp_dir='tmp')
```

complains it cannot find the .map file which should be generated by gem-mapper in the tmp directory. I’ve tried to run gem-mapper as standalone

```
gem-mapper -I 737_int_hg19.gem -q offset-33 -m 0.04 -s 0 --allow-incomplete-strata 0.00 --granularity 10000 --max-decoded-matches 1 --min-decoded-strata 0 --min-insert-size 0 --max-insert-size 0 --min-matched-bases 0.8 --gem-quality-threshold 26 --max-big-indel-length 15 --mismatch-alphabet ACGT -E 0.30 --max-extendable-matches 20 --max-extensions-per-match 1 -e 0.04 -T 8 -i /lustre2/scratch/dcittaro/Volpin/HiC/Sample_44/tmp/1_S1_L001_R1_001_doROM4 -o /lustre2/scratch/dcittaro/Volpin/HiC/Sample_44/tmp/1_S1_L001_R1_001_doROM4_full_1-150
```

which complains that `--allow-incomplete-strata` is not a valid option. GEM version is v3.6.1-2-g3139-dirty-release

**Comment by fransua** [comment]
Hi Davide,
this is the first time I see this error. Thanks for reporting!
And yes you are probably right, it might be a problem of version of GEM.
can you reinstall it?
We have here: https://github.com/3DGenomes/3DAROC/blob/master/Notebooks/A0-Preparing%20your%20computer%20for%20HiC%20data%20analysis.ipynb
a tutorial to install all dependencies... including the compatible version of GEM.

cheers

**Comment by dawe** [comment]
Yep, I saw it later. What’s wrong with more recent version of GEM? Would it be possible to wrap it as well? I assume older versions won’t be fixed/updated if bugs arise

**Comment by fransua** [comment]
We are working on the integration with GEM3,and other mappers... nothing is wrong with GEM3 at all!!! :)
