### ISSUE TITLE
TADbit output to JuiceBox

### ISSUE THREAD

**Issue by mictadlo** [3DGenomes/TADbit#278]
Hi, 
Is there a way to load TADbit output to [JuiceBox](https://github.com/aidenlab/Juicebox) to extract chromosome groups?

Thank you in advance,

Michal

**Comment by david-castillo** [comment]
Hello,

There's no direct format output to JuiceBox. 
An option would be to use the tsv file TADbit generates after the filtering step http://3dgenomes.github.io/TADbit/tutorial/tutorial_0_mapping.html#filter-reads .
There you have all the information you need to use their loader except the mapping quality https://github.com/aidenlab/juicer/wiki/Pre .

Another option would be to use the write_matrix function from the hic_data object, but then you don't get the restriction enzymes positions, but should also work in the loader.

Regards

David

**Comment by fransua** [comment]
issue to be followed at https://github.com/3DGenomes/TADbit/issues/256
