### ISSUE TITLE
Error in load chromosome

### ISSUE THREAD

**Issue by lauradmartens** [3DGenomes/TADbit#320]
Hey! 

I saved a chromosome object and was trying to load it using the load_chromosome function: However, I encountered the following error:
`Can't get attribute 'RelativeChromosomeSize' on <module 'pytadbit.chromosome' from '/home/ldm41/src/miniconda3/envs/py3/lib/python3.6/site-packages/pytadbit/chromosome.py'>`

Do you know what could have happened?

All the best and thanks a lot!
Laura

**Comment by lauradmartens** [comment]
I solved it, I saved the data with an older version of Tadbit and was trying to load it with the newer version

**Comment by david-castillo** [comment]
Good, thanks
