### ISSUE TITLE
How to save the output ?

### ISSUE THREAD

**Issue by CaiCheng1996** [3DGenomes/TADbit#322]
Could anyone be so kind to tell me how to save the output ? 
I failed using plt.savefig with matplotlib, it just gave me an empty file

**Comment by fransua** [comment]
Hi @CaiCheng1996 ,
use the savefig parameter with the path to the wanted output file. The extension of the file to be created will define the format of the image (example: lala.png or lala.pdf)

**Comment by CaiCheng1996** [comment]
thank you
