### ISSUE TITLE
 Bins to genomic coordinates

### ISSUE THREAD

**Issue by aalvarezf** [3DGenomes/TADbit#328]
Hi there,

Congratulations for your tool, we find it very useful in the lab.

I have a question regarding genomic binarization. Are coordinates 0-based, as the default python behavior, or are 1-based bins?
When I write  the results from the Insulation Score calculation, the first position (pos column) is 0. However, for TADs and Compartments is not so clear because we miss some positions at the chrom ends. I guess the binarization is the same for all the positions, but could you clarify this for me please?

Thanks and sorry for this naive question, I'm not very familiar with the package.

**Comment by david-castillo** [comment]
Hi,

I guess there's a bit of inconsistency between insulation score and the TADs and compartments.
For TADs and compartments bin number 1 gets all the positions from 0 up to resolution as a half-open region (excluding reads starting exactly at resolution).
As you say for the insulation score bin number starts at 0 and should be called 1 to be consistent with TADs and compartments.

Regards

David

**Comment by aalvarezf** [comment]
Ok, thank you for the quick answer.

Regards,
Alba
