### ISSUE TITLE
gem error

### ISSUE THREAD

**Issue by shiyi-pan** [3DGenomes/TADbit#336]
Hi, I run the gem-indexer command as following:

GEM=/ds3512/home/panyp/ruanjian/GEM-binaries-Linux-x86_64-core_i3
$GEM/gem-indexer -t 4 -i NN1138-2.v1.0.genome.fasta -o NN1138-2.v1.0.genome

and met an error like that:

Welcome to GEM-indexer build 1.335 (beta) - (2012-10-29 22:24:35 GMT)
 (c) 2008-2012 Paolo Ribeca <paolo.ribeca@gmail.com>
 (c) 2010-2012 Santiago Marco Sola <santiagomsola@gmail.com>
 (c) 2010-2012 Leonor Frias Moya <leonor.frias@gmail.com>
For the terms of use, run the program with the option --show-license.
************************************************************************
* WARNING: this is a beta version, provided for testing purposes only; *
*          check for updates at <http://gemlibrary.sourceforge.net>.   *
************************************************************************
Creating sequence and location files...Fatal error: exception Failure("Command 'echo "-------gem-indexer_fasta2meta+cont" > NN1138-2.v1.0.genome.log && gem-indexer_fasta2meta+cont -i NN1138-2.v1.0.genome.fasta -c dna --filter-function iupac-dna --strip-unknown-bases-threshold 50 --complement-size-threshold 200000000

could you help me fix this ? thank you very much.

**Comment by shiyi-pan** [comment]
Hi, I fixed it.

**Comment by david-castillo** [comment]
Hi,

Sorry for the delay. Good you managed to fix it.
Remember that you can use gem v3 or bowtie2 if you prefer.

David

**Comment by claudiarabu** [comment]
Hi shiyi-pan,

How did you fix the error? I'm having the same issue.

Claudia

**Comment by Rytian57** [comment]
> Hi, I fixed it.

Hi, sorry it's been almost two years since this thread started. Could I ask how you fixed this error? I am encountering the same error and could not figure out why. Thank you so much!

**Comment by Cissi-B** [comment]
> Hi, I fixed it.

Hi, I am also encountering the same problem and have not been able to solve it. It would be very appreciated if you could explain how you solved the error. Thank you!
