### ISSUE TITLE
use TADbit on Capture Hi-C dataset

### ISSUE THREAD

**Issue by jazberna1** [3DGenomes/TADbit#342]
Dear TADbit developers,

I have a Capture Hi-C experiment. I was wondering whether I can use TADbit to process as it if was a whole genome experiment.

Thanks
Jorge

**Comment by david-castillo** [comment]
Hi Jorge,

You can use TADbit for mapping, parsing and filtering.
If you want to do modelling check an excellent work by a former member of the group here: https://github.com/julenmendieta/SparseDataModelling

Regards

David

**Comment by jazberna1** [comment]
Hello David,

Thanks so much !
Jorge
