### ISSUE TITLE
tadbit map ValueError

### ISSUE THREAD

**Issue by eng3001** [3DGenomes/TADbit#344]
I conda installed TADbit using the directions on your website and have been trying to run tadbit map and have been continuously running into the following error:
`ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False`

Commands used:
`tadbit map -w MAP_DIR --fastq s_obliquus_S3HiC_R1_clean.fastq --index assembly.fasta --read 1 --cpus 6 --renz Sau3AI`
 `tadbit map -w MAP_DIR --fastq s_obliquus_S3HiC_R2_clean.fastq --index assembly.fasta --read 2 --cpus 6 --renz Sau3AI`
`tadbit map -w DUAL_MAP_DIR --fastq s_obliquus_S3HiC_R2_clean.fastq --fastq2 s_obliquus_S3HiC_R2_clean.fastq --genome GENOME --index assembly.fasta --read 0 --cpus 6 --renz Sau3AI`

TADbit output:
Writing versions of TADbit and dependencies
Generating Hi-C QC plot
  - Dangling-ends (sensu-stricto): 0.583%
  - Ligation sites: 24.374%
mapping s_obliquus_S3HiC_R2_clean.fastq read 0 to DUAL_MAP_DIR
Writing log to DUAL_MAP_DIR/process.log
Preparing FASTQ file
  - conversion to MAP format
Mapping reads in window 1-end_8dabe42a4f...
TO GEM 3 /panfs/biopan04/scratch-wyatte/3d_HiC_Dir/3.8.21_HiCExplorer/TADBIT_DIR/DUAL_MAP_DIR_tmp_r0_8dabe42a4f/s_obliquus_S3HiC_R2_clean_xkn9etb9
/home/wyatte/.conda/envs/tadbit/bin/gem-mapper -I /panfs/biopan04/scratch-wyatte/3d_HiC_Dir/3.8.21_HiCExplorer/TADBIT_DIR/assembly.fasta -t 6 -F SAM -o /panfs/biopan04/scratch-wyatte/3d_HiC_Dir/3.8.21_HiCExplorer/TADBIT_DIR/DUAL_MAP_DIR_tmp_r0_8dabe42a4f/s_obliquus_S3HiC_R2_clean_xkn9etb9_full_1-end_8dabe42a4f.map -i /panfs/biopan04/scratch-wyatte/3d_HiC_Dir/3.8.21_HiCExplorer/TADBIT_DIR/DUAL_MAP_DIR_tmp_r0_8dabe42a4f/s_obliquus_S3HiC_R2_clean_xkn9etb9
Parsing result...
Traceback (most recent call last):
  File "/home/wyatte/.conda/envs/tadbit/bin/tadbit", line 152, in <module>
    main(sys.argv)
  File "/home/wyatte/.conda/envs/tadbit/bin/tadbit", line 149, in main
    args.func(args)
  File "/home/wyatte/.conda/envs/tadbit/lib/python3.7/site-packages/pytadbit/tools/tadbit_map.py", line 106, in run
    mapper_params=opts.mapper_param)
  File "/home/wyatte/.conda/envs/tadbit/lib/python3.7/site-packages/pytadbit/mapping/full_mapper.py", line 655, in full_mapping
    base_name + '_full_%s-%s%s.map' % (beg, end, suffix)))
  File "/home/wyatte/.conda/envs/tadbit/lib/python3.7/site-packages/pytadbit/mapping/full_mapper.py", line 283, in _sam_filter
    fhandler = Samfile(fnam)
  File "pysam/libcalignmentfile.pyx", line 741, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 990, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False
Command exited with non-zero status 1

Any information on how to get around this error would be extremely helpful. Thank you!

**Comment by david-castillo** [comment]
Hi,

This is correct

`tadbit map -w MAP_DIR --fastq s_obliquus_S3HiC_R1_clean.fastq --index assembly.fasta --read 1 --cpus 6 --renz Sau3AI`

However for --index you have to use the gem (or bowtie2, hisat2) index not the fasta.
In the case of gem you have to use the gem-indexer command line but every mapper has its own indexer.

Regards

David

**Comment by eng3001** [comment]
Thank you for the help!
Best, Wyatt

**Comment by eng3001** [comment]
I have tried building an index for the genome using bowtie2 and hisat2 using the fallowing commands:
`hisat2-build --threads 24 assembly.fasta S_obliquus`
`bowtie2-build assembly.fasta Scenedesmus_obliquus`

I then tried to feed the index builder output path to `tadbit map` but continue to get the same error. Tadbit map command:
```/usr/bin/time -v tadbit map -w MAP_DIR --fastq s_obliquus_S3HiC_R1_clean.fastq --index HiSat2_Index --read 1 --cpus 6 --renz Sau3AI
/usr/bin/time -v tadbit map -w MAP_DIR --fastq s_obliquus_S3HiC_R2_clean.fastq --index HiSat2_Index --read 2 --cpus 6 --renz Sau3AI```

tadbit map `--index` seems to be searching for an actual .index file in those directories. I will try to use gem-indexer.

**Comment by david-castillo** [comment]
I guess HiSat2_Index is the folder, you have to put it this way:

--index HiSat2_Index/S_obliquus

**Comment by eng3001** [comment]
Command:
`tadbit map -w MAP_DIR --fastq s_obliquus_S3HiC_R1_clean.fastq --index HiSat2_Index/S_obliquus --read 1 --cpus 6 --renz Sau3AI`

Error:
```
Traceback (most recent call last):
  File "/home/wyatte/.conda/envs/tadbit/bin/tadbit", line 152, in <module>
    main(sys.argv)
  File "/home/wyatte/.conda/envs/tadbit/bin/tadbit", line 149, in main
    args.func(args)
  File "/home/wyatte/.conda/envs/tadbit/lib/python3.7/site-packages/pytadbit/tools/tadbit_map.py", line 47, in run
    check_options(opts)
  File "/home/wyatte/.conda/envs/tadbit/lib/python3.7/site-packages/pytadbit/tools/tadbit_map.py", line 228, in check_options
    raise IOError('ERROR: index file not found at ' + opts.index)
OSError: ERROR: index file not found at HiSat2_Index/S_obliquus
```

I still get the following error when trying to pass the index into tadbit map.

**Comment by fransua** [comment]
Hi,
Hisat2 does not want a folder, but a truncated file name... 
For example, on my computer I have these files when building the index:
```
Homo_sapiens-GRCh38.p13.ht2.1.ht2
Homo_sapiens-GRCh38.p13.ht2.2.ht2
Homo_sapiens-GRCh38.p13.ht2.3.ht2
Homo_sapiens-GRCh38.p13.ht2.4.ht2
Homo_sapiens-GRCh38.p13.ht2.5.ht2
Homo_sapiens-GRCh38.p13.ht2.6.ht2
Homo_sapiens-GRCh38.p13.ht2.7.ht2
Homo_sapiens-GRCh38.p13.ht2.8.ht2
```
and to work with this, I pass to TADbit: `--index Homo_sapiens-GRCh38.p13.ht2`

**Comment by eng3001** [comment]
Hello,
Thank you for the help. I have hisat2 files named:
```
S_obliquus.1.ht2
S_obliquus.2.ht2
S_obliquus.3.ht2
S_obliquus.4.ht2
S_obliquus.5.ht2
S_obliquus.6.ht2
S_obliquus.7.ht2
S_obliquus.8.ht2
```
and tried `--index HiSat2_Index/S_obliquus.ht2` and am still running into the following error: 
`OSError: ERROR: index file not found at HiSat2_Index/S_obliquus.ht2`

**Comment by fransua** [comment]
Ok,
than I understand it should be `--index HiSat2_Index/S_obliquus` as you tried before...
Can you try the same command adding `--mapper hisat2 --index HiSat2_Index/S_obliquus`

**Comment by eng3001** [comment]
Thank you all for the help! `--mapper hisat2 --index HiSat2_Index/S_obliquus` ran successfully.
