### ISSUE TITLE
Problem with the weight values in cooler output

### ISSUE THREAD

**Issue by vntasis** [3DGenomes/TADbit#359]
Hi,

After using 'tadbit export' to extract cooler files of specific chromosomes, I wanted to check the output. Initially I wanted to check the weight values. So, I used the 'cooler dump' command to get the bins table. The fact that surprised me is that the column of weights was exactly the same for two different samples. Also, If I am not wrong the weights of the cooler file are supposed to be just the inverse of the biases saved inside the bias pickle file produced by 'tadbit normalize' (apart from 0s). This does not seem to be the case. Maybe I miss something obvious. I would really appreciate it, if you could help me.

Thanks

**Comment by david-castillo** [comment]
Hi,

I'll check the code. There might be bugs on there.
Have you tried to export the full matrix? 

Regards

David

**Comment by vntasis** [comment]
Not really. I was doing it on a per chromosome basis for parallelization purposes. I will try it and let you know.

**Comment by david-castillo** [comment]
It might be that the bug is coming when selecting the biases from a specific chromosome. I'll check anyway.

**Comment by david-castillo** [comment]
Ok, I spotted the error. 
I've pushed a hot-fix.

You will need to reinstall TADbit to see the changes.
Please try and let me know.

**Comment by vntasis** [comment]
It seems that the problem is fixed. I will run some more tests the next days and then I will close the issue.

Thank you very much for all the help and the quick response.
