### ISSUE TITLE
failure with Parameter optimization for IMP

### ISSUE THREAD

**Issue by gaofan83** [3DGenomes/TADbit#73]
Hi there,
I got an issue when running the following command on Ubuntu (part of a script). See below

optimizer = exp.optimal_imp_parameters(1, 250, n_cpus=8, n_models=100, n_keep=20, cutoff=20000, lowfreq_range=(-1, 0, 0.2), upfreq_range=(0, 1, 0.2), maxdist_range=(20000, 35000, 3000), verbose=True)

TypeError: optimal_imp_parameters() got an unexpected keyword argument 'cutoff'

And when I tried the following command, the same problem happened:

optimizer = IMPoptimizer(exp, 1, 250, n_models=100, n_keep=20,cutoff=20000)

TypeError: **init**() got an unexpected keyword argument 'cutoff'

Not sure what was wrong. Thanks.

**Comment by fransua** [comment]
Hi @gaofan83 ,
what is wrong is the documentation, I still haven't updated it. Now the optimal_imp_parameter get the dcutoff_range parameter instead. It's default value is 2, and it is dependent on the radius of the bead (resolution times scale), 2 means two times 10000 times 0.01 for a resolution of 10Kb and a scale of 0.01.
the IMPoptimizer class does not take any cutoff parameter. they are directly passed to the run_grid_search function.
I will do my best to update the documentation soon, I am sorry TADbit is still in development. 
thanks

**Comment by mcmccon** [comment]
Any updates on updating the documentation? I ran into the same problem, not sure from your comment where is the dcutoff_range parameter.

Thanks

**Comment by fransua** [comment]
Hi @mcmccon 
yes, the documentation is ready, we have to replace it now.
in the meanwhile you can find it in notebooks there: https://github.com/3DGenomes/MethodsMolBiol

And in particular, about your dcutoff question, you should find an answer there:
https://github.com/3DGenomes/MethodsMolBiol/blob/master/Notebooks/Methods-10-Modeling%20parameters%20optimization.ipynb

let us know if it helps

cheers

**Comment by mcmccon** [comment]
Thank you very much!
