### ISSUE TITLE
Visualize returns error when calling view

### ISSUE THREAD

**Issue by kipal1988** [3DGenomes/tadbit#88]
When calling visualize on chromosome object the function produces an error because it provides a cmap variable in the call, which is not present in the view function.

This happens when calling two experiments together. Like so, my_chrom.visualize([('50kbRes','100kbRes')],paint_tads=True)

**Comment by fransua** [comment]
thanks for reporting this issue @kipal1988,
it shouldn't take too long to fix it.

**Comment by fransua** [comment]
Hi @kipal1988 ,
I was not able to reproduce the bug you are reporting, with the current version of TADbit. Can you please let me know the version (inside the README, or import pytadbit; print pytadbit.__version__).
thanks
