### ISSUE TITLE
Invalid DISPLAY variable for `hic_map`

### ISSUE THREAD

**Issue by Tong-Chen** [3DGenomes/TADbit#96]
Dear Francois,

I ran `TADbit` on a remote server.

When running `hic_map`, it returns a `RuntimeError: Invalid DISPLAY variable`. In my `bash`, $DISPLAY contains nothing.

Here is the full error messages:

```
hic_map('/home/name/name/Projects/TADs/test/SRR_test_1000000/reads12_SRR_test.tsv', resolution=1000000, normalized=False, masked=None, by_chrom='all', savefig='/home/name/name/Projects/TADs/hic_map/', show=False, savedata='/home/name/name/Projects/TADs/hic_map/', focus=None, clim=None, cmap='tadbit', decay=True, perc=10, name='name')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/name/name/software/anaconda/lib/python2.7/site-packages/pytadbit/mapping/analyze.py", line 105, in hic_map
    name=name, cistrans=float('NaN'))
  File "/home/name/name/software/anaconda/lib/python2.7/site-packages/pytadbit/mapping/analyze.py", line 143, in draw_map
    ctfig = plt.figure(figsize=(15.,12.5))
  File "/home/name/name/software/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 434, in figure
    **kwargs)
  File "/home/name/name/software/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 47, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/home/name/name/software/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 54, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/home/name/name/software/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 72, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/home/name/name/software/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
    _create_qApp()
  File "/home/name/name/software/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 139, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable

```

Then I searched these error messages and found a general solution by using _matplotlib('Agg')_. However, it give another error information.

```
>>> import matplotlib
>>> matplotlib.use('Agg') # do this before importing pyplot
>>> from matplotlib import pyplot
>>> pyplot.ioff()
>>> from pytadbit.mapping.analyze import hic_map
>>> hic_map('/home/name/name/Projects/TADs/test/SRR_test_1000000/reads12_SRR_test.tsv', resolution=1000000, normalized=False, masked=None, by_chrom='all', savefig='/home/name/name/Projects/TADs/hic_map/', show=False, savedata='/home/name/name/Projects/TADs/hic_map/', focus=None, clim=None, cmap='tadbit', decay=True, perc=10, name='name')
/home/name/name/software/anaconda/lib/python2.7/site-packages/pytadbit/mapping/analyze.py:170: RuntimeWarning: invalid value encountered in double_scalars
  median = (np.median(vals) - mindata) / diff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/name/name/software/anaconda/lib/python2.7/site-packages/pytadbit/mapping/analyze.py", line 105, in hic_map
    name=name, cistrans=float('NaN'))
  File "/home/name/name/software/anaconda/lib/python2.7/site-packages/pytadbit/mapping/analyze.py", line 172, in draw_map
    pos = (np.percentile(vals, prc * 100.) - mindata) / diff
  File "/home/name/name/software/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3042, in percentile
    interpolation=interpolation)
  File "/home/name/name/software/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2791, in _ureduce
    r = func(a, **kwargs)
  File "/home/name/name/software/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3130, in _percentile
    ap.partition(concatenate((indices_below, indices_above)), axis=axis)
ValueError: kth(=-9223372036854775807) out of bounds (1)
>>> 
```

I do not why. Could you please help me?

Thanks!

Best,

Chen Tong

**Comment by fransua** [comment]
Hi Chen Tong,
I am afraid I forgot to remove the "all" option from the hic_map
documentation.
Can you try to call the function 2 times, once with intra, and once with
inter. This is actually how I do it.
sorry for the bug, I'll try to find a solution.
cheers,
francois

ps: not sure you need the pyplot.ioff()


On 27 March 2015 at 03:11, Chen Tong <notifications@github.com> wrote:

> Dear Francois,
>
> I ran TADbit on a remote server.
>
> When running hic_map, it returns a RuntimeError: Invalid DISPLAY variable.
> In my bash, $DISPLAY contains nothing.
>
> Here is the full error messages:
>
> hic_map('/home/name/name/Projects/TADs/test/SRR_test_1000000/reads12_SRR_test.tsv', resolution=1000000, normalized=False, masked=None, by_chrom='all', savefig='/home/name/name/Projects/TADs/hic_map/', show=False, savedata='/home/name/name/Projects/TADs/hic_map/', focus=None, clim=None, cmap='tadbit', decay=True, perc=10, name='name')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/name/name/software/anaconda/lib/python2.7/site-packages/pytadbit/mapping/analyze.py", line 105, in hic_map
>     name=name, cistrans=float('NaN'))
>   File "/home/name/name/software/anaconda/lib/python2.7/site-packages/pytadbit/mapping/analyze.py", line 143, in draw_map
>     ctfig = plt.figure(figsize=(15.,12.5))
>   File "/home/name/name/software/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 434, in figure
>     **kwargs)
>   File "/home/name/name/software/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 47, in new_figure_manager
>     return new_figure_manager_given_figure(num, thisFig)
>   File "/home/name/name/software/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 54, in new_figure_manager_given_figure
>     canvas = FigureCanvasQTAgg(figure)
>   File "/home/name/name/software/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 72, in __init__
>     FigureCanvasQT.__init__(self, figure)
>   File "/home/name/name/software/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
>     _create_qApp()
>   File "/home/name/name/software/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 139, in _create_qApp
>     raise RuntimeError('Invalid DISPLAY variable')
> RuntimeError: Invalid DISPLAY variable
>
>
> Then I searched these error messages and found a general solution by using
> *matplotlib('Agg')*. However, it give another error information.
>
> >>> import matplotlib
> >>> matplotlib.use('Agg') # do this before importing pyplot
> >>> from matplotlib import pyplot
> >>> pyplot.ioff()
> >>> from pytadbit.mapping.analyze import hic_map
> >>> hic_map('/home/name/name/Projects/TADs/test/SRR_test_1000000/reads12_SRR_test.tsv', resolution=1000000, normalized=False, masked=None, by_chrom='all', savefig='/home/name/name/Projects/TADs/hic_map/', show=False, savedata='/home/name/name/Projects/TADs/hic_map/', focus=None, clim=None, cmap='tadbit', decay=True, perc=10, name='name')
> /home/name/name/software/anaconda/lib/python2.7/site-packages/pytadbit/mapping/analyze.py:170: RuntimeWarning: invalid value encountered in double_scalars
>   median = (np.median(vals) - mindata) / diff
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/name/name/software/anaconda/lib/python2.7/site-packages/pytadbit/mapping/analyze.py", line 105, in hic_map
>     name=name, cistrans=float('NaN'))
>   File "/home/name/name/software/anaconda/lib/python2.7/site-packages/pytadbit/mapping/analyze.py", line 172, in draw_map
>     pos = (np.percentile(vals, prc * 100.) - mindata) / diff
>   File "/home/name/name/software/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3042, in percentile
>     interpolation=interpolation)
>   File "/home/name/name/software/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2791, in _ureduce
>     r = func(a, **kwargs)
>   File "/home/name/name/software/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3130, in _percentile
>     ap.partition(concatenate((indices_below, indices_above)), axis=axis)
> ValueError: kth(=-9223372036854775807) out of bounds (1)
> >>>
>
> I do not why. Could you please help me?
>
> Thanks!
>
> Best,
>
> Chen Tong
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3DGenomes/tadbit/issues/96>.
>



-- 

 *François Serra *
**Postdoctoral Fellow**

   *Structural Genomics Tea**m - CNAG *- Centre Nacional d’Anàlisi Genòmica
*Structural Genomics Group - CRG *- Centre de Regulació Genòmica
Parc Científic de Barcelona – Torre I
Baldiri Reixac, 4
08028 Barcelona
Tel: +34 934 020 828

**Comment by Tong-Chen** [comment]
Dear Francois,

Using command `hic_map('/home/name/name/Projects/TADs/test/SRR_test_1000000/reads12_SRR_test.tsv', resolution=1000000, normalized=False, masked=None, by_chrom='all', show=False, savedata='/home/name/name/Projects/TADs/hic_map/', focus=None, clim=None, cmap='tadbit', decay=True, perc=10, name='name')` will output the interaction matrixes.

However, when doing the plot, there are two types of errors.

`hic_map('/home/name/name/Projects/TADs/test/SRR_test_1000000/reads12_SRR_test.tsv', resolution=1000000, normalized=False, masked=None, by_chrom='all', show=False, savefig='/home/name/name/Projects/TADs/hic_map/', savedata='/home/name/name/Projects/TADs/hic_map/', focus=None, clim=None, cmap='tadbit', decay=True, perc=10, name='name')`

or

`hic_map('/home/name/name/Projects/TADs/test/SRR_test_1000000/reads12_SRR_test.tsv', resolution=1000000, normalized=False, masked=None, by_chrom='inter', show=False, savefig='/home/name/name/Projects/TADs/hic_map/', savedata='/home/name/name/Projects/TADs/hic_map/', focus=None, clim=None, cmap='tadbit', decay=True, perc=10, name='name')`

or 

``hic_map('/home/name/name/Projects/TADs/test/SRR_test_1000000/reads12_SRR_test.tsv', resolution=1000000, normalized=False, masked=None, by_chrom='intra', show=False, savefig='/home/name/name/Projects/TADs/hic_map/', savedata='/home/name/name/Projects/TADs/hic_map/', focus=None, clim=None, cmap='tadbit', decay=True, perc=10, name='name')``

1. `invalid DISPLAY variable` when executing `_ = plt.figure(figsize=(15.,12.5))`. I am running the command at a remote server without X-window and trying to save the figure into a file. I tried to use `matplotlib.use('Agg')` to solve the question, but error type2 happened.

2. `ValueError: kth(=-9223372036854775807) out of bounds (1)` when using `matplotlib('Agg')` before running `hic_map`. This `ValueError` is caused partly by `diff==0` in `median = (np.median(vals) - mindata) / diff`. I do not know why `diff` would be 0.

Could you please tell me what is going wrong?

Thanks!

Tong

**Comment by Tong-Chen** [comment]
Dear Francois,

I wonder if there is any update to my puzzles. Thanks!

Best

Tong
